"use client";
import Link from "next/link";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { getInitials } from "@/lib/profile-utils";
import type { Project } from "@/lib/projects";

type EventItem = { id:string; title:string; starts_at:string; ends_at:string|null; notes:string|null; project_id:string|null };
type Props = { name:string; projects:Project[]; crew:Project[]; counts:{projects:number|null;crew:number|null;incoming:number|null;pending:number|null}; errors:boolean[] };
const dayKey=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;
const statusLabel=(v:string)=>v[0].toUpperCase()+v.slice(1);
function Shape({ kind }: {kind:string}) { return <svg className={`stat-shape ${kind}`} viewBox="0 0 100 100" aria-hidden="true">{kind==="cross"?<path d="M42 4h16v38h38v16H58v38H42V58H4V42h38z"/>:kind==="circle"?<circle cx="50" cy="50" r="47"/>:kind==="star"?<path d="M50 0 61 34 94 15 72 44 100 50 72 57 94 85 61 67 50 100 39 67 6 85 28 57 0 50 28 44 6 15 39 34z"/>:<path d="M4 10h92L50 92z"/>}</svg>; }
function Stat({label,count,kind,error}: {label:string;count:number|null;kind:string;error:boolean}) {return <div className={`home-stat ${kind}`}><Shape kind={kind}/><span>{label}</span><strong>{count===null?"—":count}</strong>{error?<small className="stat-error">Unavailable</small>:null}</div>}

export function HomeDashboard({name,projects,crew,counts,errors}:Props) {
  const [selected,setSelected]=useState(projects[0]?.id??""); const project=projects.find(p=>p.id===selected)??projects[0]; const firstName=name.trim().split(/\s+/)[0];
  const [month,setMonth]=useState(()=>new Date(new Date().getFullYear(),new Date().getMonth(),1)); const [day,setDay]=useState(dayKey(new Date())); const [events,setEvents]=useState<EventItem[]>([]); const [loadingEvents,setLoadingEvents]=useState(false); const [eventError,setEventError]=useState(false); const [modal,setModal]=useState(false); const [editing,setEditing]=useState<EventItem|null>(null); const [saving,setSaving]=useState(false); const [formError,setFormError]=useState(""); const dialog=useRef<HTMLDialogElement>(null);
  const range=useMemo(()=>{const start=new Date(month.getFullYear(),month.getMonth(),1);start.setDate(start.getDate()-((start.getDay()+6)%7));const end=new Date(start);end.setDate(end.getDate()+42);return {start,end};},[month]);
  const fetchEvents=useCallback(async()=>{setLoadingEvents(true);setEventError(false);try{const response=await fetch(`/api/events?from=${encodeURIComponent(range.start.toISOString())}&to=${encodeURIComponent(range.end.toISOString())}`);if(!response.ok)throw new Error();const data=await response.json();setEvents(data.events??[]);}catch{setEventError(true);}finally{setLoadingEvents(false);}},[range]);
  useEffect(()=>{const timer=window.setTimeout(()=>{void fetchEvents();},0);return()=>window.clearTimeout(timer);},[fetchEvents]);
  useEffect(()=>{if(modal){dialog.current?.showModal();}else if(dialog.current?.open){dialog.current.close();}},[modal]);
  useEffect(()=>{const close=()=>{setModal(false);setEditing(null);setFormError("");};const d=dialog.current;d?.addEventListener("close",close);return()=>d?.removeEventListener("close",close);},[]);
  const eventDays=new Set(events.map(e=>dayKey(new Date(e.starts_at)))); const todaysEvents=events.filter(e=>dayKey(new Date(e.starts_at))===day); const calendarDays=Array.from({length:42},(_,i)=>{const d=new Date(range.start);d.setDate(d.getDate()+i);return d;});
  const openEvent=(item?:EventItem)=>{setEditing(item??null);setFormError("");setModal(true);};
  const saveEvent=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();setSaving(true);setFormError("");const form=new FormData(e.currentTarget);const local=`${form.get("date")}T${form.get("time")||"09:00"}`;const startsAt=new Date(local);if(!form.get("title")||Number.isNaN(startsAt.getTime())){setFormError("Enter a title and a valid date.");setSaving(false);return;}const payload={...(editing?{id:editing.id}:{}),title:String(form.get("title")),startsAt:startsAt.toISOString(),projectId:String(form.get("project")||"")||null,notes:String(form.get("notes")||"")||null};try{const response=await fetch("/api/events",{method:editing?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});if(!response.ok){const d=await response.json();throw new Error(d.error||"Unable to save event");}setModal(false);await fetchEvents();}catch(err){setFormError(err instanceof Error?err.message:"Unable to save event");}finally{setSaving(false);}};
  const removeEvent=async(id:string)=>{try{const r=await fetch(`/api/events?id=${encodeURIComponent(id)}`,{method:"DELETE"});if(!r.ok)throw new Error();await fetchEvents();}catch{setEventError(true);}};
  const done=[projects.length>0,projects.some(p=>p.skills.length>0),counts.incoming===0];const next=done.findIndex(x=>!x);const nextHref=next===0?"/projects/new":next===1?(project?`/projects/${project.id}/edit`:"/projects/new"):"/applications";
  return <div className="home-dashboard"><div className="home-main"><header className="home-welcome"><h1>Welcome back, {firstName}.</h1><p>A little progress today can turn into something great tomorrow.</p></header>
    <section className="home-stats" aria-label="Your CrewLab activity"><Stat label="My Projects" count={counts.projects} kind="red" error={errors[0]}/><Stat label="My Crew" count={counts.crew} kind="black" error={errors[1]}/><Stat label="Incoming Applications" count={counts.incoming} kind="white" error={errors[2]}/><Stat label="Pending Applications" count={counts.pending} kind="gray" error={errors[3]}/></section>
    <section className="home-projects"><div className="home-section-heading"><h2>My projects</h2><Link href="/my-projects" className="black-pill">View all <span aria-hidden="true">→</span></Link></div>
      {errors[0]?<div className="home-state" role="alert">We couldn&apos;t load your projects. Please refresh to try again.</div>:projects.length?<div className="project-showcase"><div className="project-list">{projects.slice(0,4).map((p)=>{const selectedRow=(project?.id===p.id);return <button key={p.id} onClick={()=>setSelected(p.id)} className={`project-row ${selectedRow?"is-selected":""}`} aria-pressed={selectedRow}><span className="project-row-mark"><svg viewBox="0 0 24 24"><path d="m12 2 9 5v10l-9 5-9-5V7z"/></svg></span><span className="project-row-copy"><b>{p.title}</b><small>{p.short_description}</small></span><span className="project-row-status">{statusLabel(p.status)}</span></button>;})}<Link href="/projects/new" className="start-project-row">+ Start another project</Link><div className="project-crew-note"><b>Crew of {project?.crew_count ?? 0}</b><span>Updated {project?new Date(project.updated_at).toLocaleDateString():""}</span><span className="owner-avatar">{getInitials(project?.owner?.display_name||name,project?.owner?.username)}</span></div></div>
        {project?<article className="project-detail"><div className="project-detail-head"><Link href={`/projects/${project.id}`}><h3>{project.title}</h3></Link><span>{statusLabel(project.status)}</span></div><p className="project-owner">Owner - {project.owner?.display_name||name}{project.owner?.username?` (@${project.owner.username})`:""}</p><div className="project-tags">{project.skills.map(s=><span key={s.id}>{s.name}</span>)}</div><div className="project-description">{project.description||project.short_description}</div></article>:null}</div>:<div className="home-empty"><h3>Every great build starts with an idea.</h3><p>Create your first project and find the people to build it with.</p><Link href="/projects/new" className="red-pill">Start a project <span>→</span></Link></div>}
    </section></div>
    <aside className="home-aside"><section className="calendar-card"><div className="calendar-head"><div><span className="calendar-month">{month.toLocaleDateString(undefined,{month:"long",year:"numeric"})}</span><p>Today - {new Date().getDate()}</p></div><div className="calendar-arrows"><button aria-label="Previous month" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}>‹</button><button aria-label="Next month" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}>›</button></div></div><div className="calendar-grid">{["Mon","Tue","Wed","Thu","Fri","Sat","Sun"].map(d=><span key={d} className="calendar-weekday">{d}</span>)}{calendarDays.map(d=><button key={dayKey(d)} onClick={()=>setDay(dayKey(d))} className={`calendar-day ${d.getMonth()!==month.getMonth()?"other-month":""} ${dayKey(d)===day?"selected-day":""} ${dayKey(d)===dayKey(new Date())?"today-day":""}`} aria-label={`${d.toLocaleDateString()}, ${eventDays.has(dayKey(d))?"has events":"no events"}`} aria-pressed={dayKey(d)===day}>{d.getDate()}{eventDays.has(dayKey(d))?<i/>:null}</button>)}</div><button className="calendar-add" onClick={()=>openEvent()}>Add event</button>{eventError?<p className="calendar-error" role="alert">Could not load events. Try refreshing.</p>:loadingEvents?<div className="skeleton-line"/>:<div className="event-agenda"><h3>{new Date(`${day}T12:00:00`).toLocaleDateString(undefined,{month:"short",day:"numeric"})}</h3>{todaysEvents.length?todaysEvents.map(e=><div key={e.id} className="agenda-event"><button onClick={()=>openEvent(e)}><b>{e.title}</b><small>{new Date(e.starts_at).toLocaleTimeString(undefined,{hour:"numeric",minute:"2-digit"})}</small></button><button aria-label={`Delete ${e.title}`} onClick={()=>removeEvent(e.id)}>×</button></div>):<p>No events for this day.</p>}</div>}</section>
      {!done.every(Boolean)?<section className="checklist-card"><h2>Get your crew moving</h2>{["Post your project idea","Add the roles you need","Review applications"].map((label,i)=><div key={label} className="checklist-row"><span className={done[i]?"is-done":""}>{done[i]?"✓":""}</span>{label}</div>)}<Link href={nextHref} className="black-pill">{next===0?"Start a project":next===1?"Add skills":"Review applications"} <span>→</span></Link></section>:null}
      <section className="my-crew-card"><div className="home-section-heading"><div><h2>My Crew</h2><p>Building together</p></div></div>{errors[1]?<div className="home-state">We couldn&apos;t load your crew.</div>:crew.length?<div className="crew-mini-list">{crew.map(p=><Link key={p.id} href={`/projects/${p.id}`}><b>{p.title}</b><small>Crew of {p.crew_count}</small></Link>)}</div>:<><p className="crew-no-join">You haven&apos;t joined a crew yet.</p><Link href="/projects" className="red-pill">Explore projects <span>→</span></Link></>}</section>
    </aside>
    <dialog ref={dialog} className="event-modal" onClick={(e)=>{if(e.target===dialog.current)setModal(false);}}><form onSubmit={saveEvent}><div className="modal-heading"><h2>{editing?"Edit event":"Add event"}</h2><button type="button" onClick={()=>setModal(false)} aria-label="Close dialog">×</button></div><label>Title<input name="title" required maxLength={120} defaultValue={editing?.title??""} autoFocus/></label><div className="event-form-grid"><label>Date<input name="date" type="date" required defaultValue={editing?dayKey(new Date(editing.starts_at)):day}/></label><label>Time<input name="time" type="time" defaultValue={editing?new Date(editing.starts_at).toTimeString().slice(0,5):"09:00"}/></label></div><label>Project (optional)<select name="project" defaultValue={editing?.project_id??""}><option value="">No project</option>{projects.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label><label>Notes<textarea name="notes" rows={3} maxLength={2000} defaultValue={editing?.notes??""}/></label>{formError?<p role="alert" className="event-form-error">{formError}</p>:null}<div className="modal-actions"><button type="button" onClick={()=>setModal(false)} className="gray-pill">Cancel</button><button className="red-pill" disabled={saving}>{saving?"Saving…":"Save event"}</button></div></form></dialog>
  </div>;
}
