-- Expand the onboarding catalog while keeping the existing slug/ID model.
-- Existing rows are updated in place so saved profile_skills links remain valid.

insert into public.skills (slug, name, sort_order) values
  ('frontend', 'Frontend Development', 1),
  ('backend', 'Backend Development', 2),
  ('full-stack', 'Full-Stack Development', 3),
  ('web-development', 'Web Development', 4),
  ('mobile', 'Mobile Development', 5),
  ('ios-development', 'iOS Development', 6),
  ('android-development', 'Android Development', 7),
  ('game-development', 'Game Development', 8),
  ('desktop-development', 'Desktop Development', 9),
  ('api-development', 'API Development', 10),
  ('devops', 'DevOps', 11),
  ('cloud-engineering', 'Cloud Engineering', 12),
  ('database-engineering', 'Database Engineering', 13),
  ('systems-programming', 'Systems Programming', 14),
  ('embedded-systems', 'Embedded Systems', 15),
  ('qa-testing', 'QA / Testing', 16),
  ('automation', 'Automation', 17),
  ('scripting', 'Scripting', 18),
  ('javascript', 'JavaScript', 19),
  ('typescript', 'TypeScript', 20),
  ('python', 'Python', 21),
  ('java', 'Java', 22),
  ('c', 'C', 23),
  ('cpp', 'C++', 24),
  ('csharp', 'C#', 25),
  ('go', 'Go', 26),
  ('rust', 'Rust', 27),
  ('php', 'PHP', 28),
  ('ruby', 'Ruby', 29),
  ('kotlin', 'Kotlin', 30),
  ('swift', 'Swift', 31),
  ('dart', 'Dart', 32),
  ('sql', 'SQL', 33),
  ('react', 'React', 34),
  ('nextjs', 'Next.js', 35),
  ('vue', 'Vue', 36),
  ('angular', 'Angular', 37),
  ('svelte', 'Svelte', 38),
  ('nodejs', 'Node.js', 39),
  ('express', 'Express', 40),
  ('django', 'Django', 41),
  ('flask', 'Flask', 42),
  ('fastapi', 'FastAPI', 43),
  ('laravel', 'Laravel', 44),
  ('spring-boot', 'Spring Boot', 45),
  ('dotnet', '.NET', 46),
  ('react-native', 'React Native', 47),
  ('flutter', 'Flutter', 48),
  ('tailwind-css', 'Tailwind CSS', 49),
  ('bootstrap', 'Bootstrap', 50),
  ('ai-ml', 'Artificial Intelligence', 51),
  ('machine-learning', 'Machine Learning', 52),
  ('deep-learning', 'Deep Learning', 53),
  ('generative-ai', 'Generative AI', 54),
  ('llms', 'LLMs', 55),
  ('computer-vision', 'Computer Vision', 56),
  ('natural-language-processing', 'Natural Language Processing', 57),
  ('data', 'Data Science', 58),
  ('data-analysis', 'Data Analysis', 59),
  ('data-engineering', 'Data Engineering', 60),
  ('mlops', 'MLOps', 61),
  ('prompt-engineering', 'Prompt Engineering', 62),
  ('aws', 'AWS', 63),
  ('google-cloud', 'Google Cloud', 64),
  ('azure', 'Azure', 65),
  ('cloudflare', 'Cloudflare', 66),
  ('docker', 'Docker', 67),
  ('kubernetes', 'Kubernetes', 68),
  ('terraform', 'Terraform', 69),
  ('ci-cd', 'CI/CD', 70),
  ('linux', 'Linux', 71),
  ('networking', 'Networking', 72),
  ('cybersecurity', 'Cybersecurity', 73),
  ('ui-design', 'UI Design', 74),
  ('ux-design', 'UX Design', 75),
  ('ui-ux', 'UI/UX', 76),
  ('product-design', 'Product Design', 77),
  ('ux-research', 'UX Research', 78),
  ('design-systems', 'Design Systems', 79),
  ('figma', 'Figma', 80),
  ('prototyping', 'Prototyping', 81),
  ('graphic-design', 'Graphic Design', 82),
  ('motion-design', 'Motion Design', 83),
  ('3d-design', '3D Design', 84),
  ('illustration', 'Illustration', 85),
  ('branding', 'Branding', 86),
  ('product', 'Product Management', 87),
  ('project-management', 'Project Management', 88),
  ('product-strategy', 'Product Strategy', 89),
  ('startup', 'Startup', 90),
  ('entrepreneurship', 'Entrepreneurship', 91),
  ('business-development', 'Business Development', 92),
  ('market-research', 'Market Research', 93),
  ('growth', 'Growth', 94),
  ('marketing', 'Marketing', 95),
  ('content-strategy', 'Content Strategy', 96),
  ('seo', 'SEO', 97),
  ('sales', 'Sales', 98),
  ('copywriting', 'Copywriting', 99),
  ('technical-writing', 'Technical Writing', 100),
  ('content-creation', 'Content Creation', 101),
  ('video-editing', 'Video Editing', 102),
  ('photography', 'Photography', 103),
  ('animation', 'Animation', 104),
  ('3d-modeling', '3D Modeling', 105),
  ('music-audio', 'Music / Audio', 106),
  ('social-media', 'Social Media', 107),
  ('git-github', 'Git / GitHub', 108),
  ('open-source', 'Open Source', 109),
  ('blockchain-web3', 'Blockchain / Web3', 110),
  ('iot', 'IoT', 111),
  ('robotics', 'Robotics', 112),
  ('ar-vr', 'AR / VR', 113),
  ('no-code-low-code', 'No-Code / Low-Code', 114),
  ('research', 'Research', 115),
  ('technical-leadership', 'Technical Leadership', 116)
on conflict (slug) do update
set name = excluded.name,
    sort_order = excluded.sort_order;
